# Generated by Django 4.1.6 on 2023-02-07 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Типы кузова',
                'verbose_name_plural': 'Типы кузова',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=100, verbose_name='Марка/Бренд')),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/brands/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Автомобильные бренды',
                'verbose_name_plural': 'Автомобильные бренды',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Модель')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('birthday', models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Год выпуска')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/car/', verbose_name='Фото')),
                ('published', models.DateTimeField(auto_now=True, verbose_name='Добавлено')),
                ('brd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.brand', verbose_name='Марка/Бренд')),
                ('btype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bodytype', verbose_name='Тип кузова')),
            ],
            options={
                'verbose_name': 'Автомобили',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Классы автомобилей',
                'verbose_name_plural': 'Классы автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='photos/countries/')),
            ],
            options={
                'verbose_name': 'Страны',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('max_speed', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)])),
                ('engine_power', models.CharField(max_length=50)),
                ('drive_unit', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('doors', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('сr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.car')),
            ],
            options={
                'verbose_name': 'Технические характеристики',
                'verbose_name_plural': 'Технические характеристики',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='carcl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.carclass', verbose_name='Класс автомобиля'),
        ),
        migrations.AddField(
            model_name='brand',
            name='countr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.country', verbose_name='Страна'),
        ),
    ]
